In [3]:
import numpy as np

In [4]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [5]:
#Get a specific elemnt [r, c]
a[0,0]

1

In [6]:
a[0,1]

2

In [8]:
a[0,2]

3

In [9]:
a[1,0]

8

In [10]:
a[1,1]

9

In [11]:
a[1,2]

10

In [12]:
#get a specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [13]:
a[1,:]

array([ 8,  9, 10, 11, 12, 13, 14])

In [14]:
a[:,3]

array([ 4, 11])

In [17]:
a[:,6]

array([ 7, 14])

In [18]:
a[:,5]

array([ 6, 13])

In [19]:
#Getting a little more fancy[startindex:endindex:srepsize]
a[0, 1:6:2]

array([2, 4, 6])

In [20]:
a[1, 5] = 20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [21]:
a[0,3] = 333
print(a)

[[  1   2   3 333   5   6   7]
 [  8   9  10  11  12  20  14]]
