In [1]:
import numpy as np

In [3]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [11]:
#Get specific element(work outside in)
b[0,1,1]

4

In [14]:
#replace
b[0,0,1] = 999
print(b)

[[[  1 999]
  [  3   4]]

 [[  5   6]
  [  7   8]]]


In [18]:
b[:,0,] = [[[44],[44]]]
print(b)

ValueError: setting an array element with a sequence.