In [1]:
import numpy as np

In [2]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [3]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [4]:
#all 1s matrix
np.ones((4,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [7]:
np.ones((4,3,2), dtype="int32")

array([[[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]]])

In [9]:
#Any other number
np.full((2,3),5, dtype='float32')

array([[5., 5., 5.],
       [5., 5., 5.]], dtype=float32)

In [11]:
#Any other number (full_like)
np.full_like(np.zeros,5)

array(5, dtype=object)

In [20]:
#random decimal numbers
np.random.rand(4,2,3)

array([[[0.27748714, 0.29102449, 0.4695618 ],
        [0.68704104, 0.66894636, 0.03915267]],

       [[0.43848918, 0.52674112, 0.75301659],
        [0.28959316, 0.83405637, 0.13686622]],

       [[0.78764963, 0.43196363, 0.62153617],
        [0.96825736, 0.63914883, 0.41441325]],

       [[0.0345189 , 0.02428841, 0.33597687],
        [0.44313732, 0.18181623, 0.83248531]]])

In [25]:
#random integer values
np.random.randint(4,6, size=(3,3))

array([[4, 5, 5],
       [5, 5, 5],
       [4, 4, 5]])

In [27]:
#the identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [38]:
#repeat an array
arr = np.array([[1,2,3],[5,3,6]])
r1 = np.repeat(arr,3,axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]
 [5 3 6]
 [5 3 6]
 [5 3 6]]


# challenge

In [47]:
output = np.ones((5,5))
#print(output)

z = np.zeros((3,3))
z [1,1] = 9
#print(z)

output [1:4,1:4] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [12]:
a = np.ones((5,5))
print(a)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [14]:
b = np.zeros((3,3))
print(b)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [15]:
b[1,1] = 9
print(b)

[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]


In [16]:
a[1:4,1:4] = b
print(a)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
