# Be careful when copying arrays!!!

In [1]:
import numpy as np

In [2]:
a = np.array([4,7,6])
a

array([4, 7, 6])

In [3]:
b = a
b

array([4, 7, 6])

In [4]:
b[0] = 63
b

array([63,  7,  6])

In [5]:
a

array([63,  7,  6])

# forma correcta de opiar array

In [6]:
c = np.array([4,7,6])
c

array([4, 7, 6])

In [7]:
d = c.copy()
d

array([4, 7, 6])

In [8]:
d[0] = 432
d

array([432,   7,   6])

In [9]:
c

array([4, 7, 6])