# Basics ops to do

## Linear algebra

In [1]:
import numpy as np

In [2]:
a = np.full((2,3),1)
print(a)

b = np.full((3,2),2)
print(b)

np.matmul(a,b)

[[1 1 1]
 [1 1 1]]
[[2 2]
 [2 2]
 [2 2]]


array([[6, 6],
       [6, 6]])

In [3]:
# Find determinant
c = np.identity(3)
np.linalg.det(c)

1.0

In [4]:
#linear algebra scipy

# Statistics

In [5]:
stats = np.array([[1,2,3],[4,5,6]])

In [6]:
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
np.max(stats, axis=1)

array([3, 6])

In [12]:
np.min(stats, axis=0)

array([1, 2, 3])

In [18]:
np.mean(stats)

3.5

In [13]:
np.sum(stats)

21

In [14]:
np.sum(stats, axis=0)

array([5, 7, 9])