### load data from file

In [1]:
import numpy as np

In [2]:
import matplotlib

In [16]:
!pwd

/c/Users/Usuario/Developer/Numpy


In [12]:
!ls

1.basics.ipynb
2.Accessing - changing specific elemnts, rows, columns, etc.ipynb
3.3D example.ipynb
4.initializing Different types of arrays.ipynb
5.Copy arrays numpy.ipynb
6.maths, alg, stats.ipynb
7.organisin.ipynb
8.miscellaneous.ipynb


In [15]:
!cd ..

In [18]:
filedata = np.genfromtxt('../../desktop/data.txt', delimiter=',')

In [24]:
filedata = filedata.astype('int32')

In [32]:
print(filedata)

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


## Boolean Masking and advance indexing

In [33]:
filedata > 50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [42]:
filedata[filedata>50]

array([196,  75, 766,  75,  55, 999,  78,  76,  88])

In [43]:
#you can index with a list in numpy
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]


array([2, 3, 9])

In [45]:
np.any(filedata > 50, axis=0)

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [46]:
np.any(filedata > 50, axis=1)

array([ True,  True,  True])

In [52]:
((filedata>50)&(filedata<100))

array([[False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [18]:
a = np.array([[1,2,3,4,5],[11,12,13,14,15]])
print(a)

[[ 1  2  3  4  5]
 [11 12 13 14 15]]


In [17]:
b = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(b)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [4]:
c = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25],[26,27,28,29,30]])
print(c)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


In [5]:
azul = c[2:4,0:2]
print(azul)

[[11 12]
 [16 17]]


In [7]:
verde = c[[0,1,2,3],[1,2,3,4]]
print(verde)

[ 2  8 14 20]


In [21]:
rojo = c[[0,4,5],3:5]
print(rojo)

[[ 4  5]
 [24 25]
 [29 30]]


In [22]:
print(np.__version__)

1.17.3


In [ ]:
import tensorflow as tf

C:\Users\Usuario\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:523: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\Usuario\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:524: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\Usuario\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\Usuario\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:526: FutureWarnin

In [ ]:
print(tf.__version__)